IF NOT EXISTS (
	SELECT 
		1 
	FROM
		INFORMATION_SCHEMA.COLUMNS T  
	WHERE
		T.TABLE_CATALOG = '<< Database >>' AND
		T.TABLE_SCHEMA = '<< Schema >>' AND
		T.TABLE_NAME = '<< Table >>' AND
		T.COLUMN_NAME = 'LastEditedBy'
)
	SELECT [Result] = CAST(1 AS BIT)
ELSE
	SELECT [Result] = CAST(0 AS BIT)